services:
  synauthproxy:
    image: okigan/synauthproxy:latest  # Use pre-built image from Docker Hub
    # For local development, uncomment the build section below and comment out the image line:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      RADIUS_SERVER: 192.168.10.12        # Change to your RADIUS server IP
                                           # If RADIUS is on the Docker host, use: 172.17.0.1
      RADIUS_SECRET: auth-proxy-secret1    # Change to your RADIUS shared secret
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: synauthproxy
      LOGIN_DOMAIN: 192.168.10.137     # Change to your Synology DDNS domain
      SYNAUTHPROXY_ADMIN_USERS: admin,user1 # Comma-separated admin users (optional)
    ports:
      - "9000:9000"
    volumes:
      - synauthproxy_config:/app/config    # Persistent config storage
      - /etc/localtime:/etc/localtime:ro

volumes:
  synauthproxy_config:
    driver: local
