services:
  synauthproxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      RADIUS_SERVER: 192.168.10.12
      RADIUS_SECRET: auth-proxy-secret1
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: auth_proxy
      LOGIN_DOMAIN: gpt.okulist.com
      SYNAUTHPROXY_ADMIN_USERS: admin,igor  # Only these users can edit mappings
    ports:
      - "9000:9000"  # HTTP/WebSocket (use 9443 for HTTPS/WSS)
    volumes:
      - ./:/app
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  app:
    driver: local
  config:
    driver: local
