# RevProxAuth Full Stack
# Complete setup with RevProxAuth, RADIUS, and test application

services:
  # RADIUS authentication server
  radius:
    image: freeradius/freeradius-server:latest
    container_name: revproxauth-radius
    restart: unless-stopped
    ports:
      - "9001:1812/udp"
    volumes:
      - ./apps/radius/config/clients.conf:/etc/raddb/clients.conf:ro
      - ./apps/radius/config/users:/etc/raddb/mods-config/files/authorize:ro
    networks:
      - auth-network

  # RevProxAuth - Python FastAPI authentication proxy
  revproxauth:
    build:
      context: ./apps/revproxauth
      dockerfile: Dockerfile
    container_name: revproxauth
    restart: unless-stopped
    environment:
      RADIUS_SERVER: radius
      RADIUS_SECRET: testing123
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: revproxauth
      LOGIN_DOMAIN: localhost:9000
      REVPROXAUTH_ADMIN_USERS: admin
    ports:
      - "9000:9000"
    volumes:
      - ./apps/revproxauth/main.py:/app/main.py
      - ./apps/revproxauth/dictionary:/app/dictionary
      - ./apps/revproxauth/templates:/app/templates
      - ./apps/revproxauth/static:/app/static
      - ./apps/revproxauth/config:/app/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - radius
      - whoami
    networks:
      - auth-network

  # Test backend application
  whoami:
    image: traefik/whoami:latest
    container_name: revproxauth-whoami
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    name: revproxauth-network
    driver: bridge
