# Docker Compose for local development
# This mounts the local directory for live code changes
# Use this for development with hot-reload

services:
  synauthproxy:
    build:
      context: ./apps/synauthproxy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      RADIUS_SERVER: 192.168.10.12
      RADIUS_SECRET: auth-proxy-secret1
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: synauthproxy
      LOGIN_DOMAIN: localhost:9000
      SYNAUTHPROXY_ADMIN_USERS: synadmin
    ports:
      - "9000:9000"
    volumes:
      # Mount individual files/dirs for live code changes
      - ./apps/synauthproxy/main.py:/app/main.py
      - ./apps/synauthproxy/dictionary:/app/dictionary
      - ./apps/synauthproxy/templates:/app/templates
      - ./apps/synauthproxy/static:/app/static
      - ./apps/synauthproxy/config:/app/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  app:
    driver: local
  config:
    driver: local
