# Docker Compose for local development
# This mounts the local directory for live code changes

services:
  synauthproxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      RADIUS_SERVER: 192.168.10.12
      RADIUS_SECRET: auth-proxy-secret1
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: synauthproxy
      LOGIN_DOMAIN: localhost:9000
      SYNAUTHPROXY_ADMIN_USERS: synadmin
    ports:
      - "9000:9000"
    volumes:
      # Mount individual files/dirs instead of entire app to preserve .venv
      - ./main.py:/app/main.py
      - ./dictionary:/app/dictionary
      - ./templates:/app/templates
      - ./static:/app/static
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  app:
    driver: local
  config:
    driver: local
