services:
  radius-auth-go:
    image: okigan/radius-auth-go:latest
    environment:
      RADIUS_SERVER: 192.168.10.12  # CHANGE THIS to your Synology IP
      RADIUS_SECRET: your-secret-here  # CHANGE THIS to match Synology RADIUS Server!
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: radius_auth_go
      SESSION_TIMEOUT: 3600

  caddy:
    image: caddy:latest
    ports:
      - "9030:80"      # Use 9030 to avoid conflict with Synology
      - "9031:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
