http:
  middlewares:
    radius-auth-go:
      forwardAuth:
        address: "http://radius-auth-go:5000/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User"

  routers:
    # Login and logout routes (no auth required)
    auth-routes:
      rule: "PathPrefix(`/login`) || PathPrefix(`/do-login`) || PathPrefix(`/logout`)"
      service: radius-auth-go
      entryPoints:
        - web

    # Protected routes - require authentication
    app:
      rule: "PathPrefix(`/`)"
      middlewares:
        - radius-auth-go
      service: whoami
      entryPoints:
        - web

  services:
    radius-auth-go:
      loadBalancer:
        servers:
          - url: "http://radius-auth-go:5000"

    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
