http:
  middlewares:
    go-radius-auth:
      forwardAuth:
        address: "http://go-radius-auth:5000/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User"

  routers:
    # Login and logout routes (no auth required)
    auth-routes:
      rule: "PathPrefix(`/login`) || PathPrefix(`/do-login`) || PathPrefix(`/logout`)"
      service: go-radius-auth
      entryPoints:
        - web

    # Protected routes - require authentication
    app:
      rule: "PathPrefix(`/`)"
      middlewares:
        - go-radius-auth
      service: whoami
      entryPoints:
        - web

  services:
    go-radius-auth:
      loadBalancer:
        servers:
          - url: "http://go-radius-auth:5000"

    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
