services:
  radius-auth-go:
    image: okigan/radius-auth-go:latest
    environment:
      RADIUS_SERVER: 192.168.10.12  # CHANGE THIS to your Synology IP
      RADIUS_SECRET: your-secret-here  # CHANGE THIS to match Synology RADIUS Server!
      RADIUS_PORT: 1812
      RADIUS_NAS_IDENTIFIER: radius_auth_go
      SESSION_TIMEOUT: 3600

  traefik:
    image: traefik:latest
    ports:
      - "9020:80"      # Use 9020 to avoid conflict with Synology
      - "9021:443"
      - "9022:8080"    # Traefik dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
